// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "index": {
      name: "index",
      description: "",
      type: "registry:style",
      registryDependencies: ["utils"],
      files: [],
      source: "",
      chunks: []
    },
    "style": {
      name: "style",
      description: "",
      type: "registry:style",
      registryDependencies: ["utils"],
      files: [],
      source: "",
      chunks: []
    },
    "animated-beam": {
      name: "animated-beam",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/animated-beam.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/animated-beam.tsx")),
      source: "",
      chunks: []
    },
    "animated-table": {
      name: "animated-table",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/animated-table.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/animated-table.tsx")),
      source: "",
      chunks: []
    },
    "bento-grid": {
      name: "bento-grid",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/bento-grid.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/bento-grid.tsx")),
      source: "",
      chunks: []
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      chunks: []
    },
    "dock": {
      name: "dock",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dock.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/dock.tsx")),
      source: "",
      chunks: []
    },
    "image-comparison": {
      name: "image-comparison",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/image-comparison.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/image-comparison.tsx")),
      source: "",
      chunks: []
    },
    "animated-tooltip": {
      name: "animated-tooltip",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/animated-tooltip.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/animated-tooltip.tsx")),
      source: "",
      chunks: []
    },
    "animated-toast": {
      name: "animated-toast",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/animated-toast.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/animated-toast.tsx")),
      source: "",
      chunks: []
    },
    "rainbow-button": {
      name: "rainbow-button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/rainbow-button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/rainbow-button.tsx")),
      source: "",
      chunks: []
    },
    "file-tree": {
      name: "file-tree",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/file-tree.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/file-tree.tsx")),
      source: "",
      chunks: []
    },
    "github-contributors": {
      name: "github-contributors",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/github-contributors.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/github-contributors.tsx")),
      source: "",
      chunks: []
    },
    "glitch-text": {
      name: "glitch-text",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/glitch-text.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/glitch-text.tsx")),
      source: "",
      chunks: []
    },
    "phone-card": {
      name: "phone-card",
      description: "",
      type: "registry:ui",
      registryDependencies: ["lazy-video"],
      files: [{
        path: "registry/default/ui/phone-card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/phone-card.tsx")),
      source: "",
      chunks: []
    },
    "rotate-text": {
      name: "rotate-text",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/rotate-text.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/rotate-text.tsx")),
      source: "",
      chunks: []
    },
    "lazy-video": {
      name: "lazy-video",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/lazy-video.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/lazy-video.tsx")),
      source: "",
      chunks: []
    },
    "vercel-tabs": {
      name: "vercel-tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/vercel-tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/vercel-tabs.tsx")),
      source: "",
      chunks: []
    },
    "magnetic": {
      name: "magnetic",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/magnetic.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/magnetic.tsx")),
      source: "",
      chunks: []
    },
    "video-player": {
      name: "video-player",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/video-player.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/video-player.tsx")),
      source: "",
      chunks: []
    },
    "calender": {
      name: "calender",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/calender.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/calender.tsx")),
      source: "",
      chunks: []
    },
    "character-morph": {
      name: "character-morph",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/character-morph.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/character-morph.tsx")),
      source: "",
      chunks: []
    },
    "code-block": {
      name: "code-block",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/code-block.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/code-block.tsx")),
      source: "",
      chunks: []
    },
    "text-morphing": {
      name: "text-morphing",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/text-morphing.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/text-morphing.tsx")),
      source: "",
      chunks: []
    },
    "scroll-text": {
      name: "scroll-text",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/scroll-text.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/scroll-text.tsx")),
      source: "",
      chunks: []
    },
    "segmented-button": {
      name: "segmented-button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/segmented-button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/segmented-button.tsx")),
      source: "",
      chunks: []
    },
    "typewritter-text": {
      name: "typewritter-text",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/typewritter-text.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/typewritter-text.tsx")),
      source: "",
      chunks: []
    },
    "velocity-morph": {
      name: "velocity-morph",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/velocity-morph.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/velocity-morph.tsx")),
      source: "",
      chunks: []
    },
    "number-counter": {
      name: "number-counter",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/number-counter.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/number-counter.tsx")),
      source: "",
      chunks: []
    },
    "highlight-text": {
      name: "highlight-text",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/highlight-text.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/highlight-text.tsx")),
      source: "",
      chunks: []
    },
    "command-palette": {
      name: "command-palette",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/command-palette.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/command-palette.tsx")),
      source: "",
      chunks: []
    },
    "github-star": {
      name: "github-star",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/github-star.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/github-star.tsx")),
      source: "",
      chunks: []
    },
    "gooey-text-morphing": {
      name: "gooey-text-morphing",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/gooey-text-morphing.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/gooey-text-morphing.tsx")),
      source: "",
      chunks: []
    },
    "feedback-widget": {
      name: "feedback-widget",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/feedback-widget.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/feedback-widget.tsx")),
      source: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-mobile.ts",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.ts")),
      source: "",
      chunks: []
    },
    "animated-beam-demo": {
      name: "animated-beam-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-beam"],
      files: [{
        path: "registry/default/examples/animated-beam-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-beam-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-beam-curved-demo": {
      name: "animated-beam-curved-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-beam"],
      files: [{
        path: "registry/default/examples/animated-beam-curved-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-beam-curved-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-beam-multiple-demo": {
      name: "animated-beam-multiple-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-beam"],
      files: [{
        path: "registry/default/examples/animated-beam-multiple-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-beam-multiple-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-beam-bidirectional-demo": {
      name: "animated-beam-bidirectional-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-beam"],
      files: [{
        path: "registry/default/examples/animated-beam-bidirectional-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-beam-bidirectional-demo.tsx")),
      source: "",
      chunks: []
    },
    "dock-demo": {
      name: "dock-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["dock"],
      files: [{
        path: "registry/default/examples/dock-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dock-demo.tsx")),
      source: "",
      chunks: []
    },
    "dock-macos-demo": {
      name: "dock-macos-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["dock"],
      files: [{
        path: "registry/default/examples/dock-macos-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dock-macos-demo.tsx")),
      source: "",
      chunks: []
    },
    "image-comparison-demo": {
      name: "image-comparison-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["image-comparison"],
      files: [{
        path: "registry/default/examples/image-comparison-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/image-comparison-demo.tsx")),
      source: "",
      chunks: []
    },
    "image-comparison-hover-demo": {
      name: "image-comparison-hover-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["image-comparison"],
      files: [{
        path: "registry/default/examples/image-comparison-hover-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/image-comparison-hover-demo.tsx")),
      source: "",
      chunks: []
    },
    "image-comparison-fade-demo": {
      name: "image-comparison-fade-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["image-comparison"],
      files: [{
        path: "registry/default/examples/image-comparison-fade-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/image-comparison-fade-demo.tsx")),
      source: "",
      chunks: []
    },
    "image-comparison-split-demo": {
      name: "image-comparison-split-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["image-comparison"],
      files: [{
        path: "registry/default/examples/image-comparison-split-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/image-comparison-split-demo.tsx")),
      source: "",
      chunks: []
    },
    "image-comparison-lens-demo": {
      name: "image-comparison-lens-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["image-comparison"],
      files: [{
        path: "registry/default/examples/image-comparison-lens-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/image-comparison-lens-demo.tsx")),
      source: "",
      chunks: []
    },
    "image-comparison-vertical-demo": {
      name: "image-comparison-vertical-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["image-comparison"],
      files: [{
        path: "registry/default/examples/image-comparison-vertical-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/image-comparison-vertical-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-tooltip-demo": {
      name: "animated-tooltip-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-tooltip"],
      files: [{
        path: "registry/default/examples/animated-tooltip-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-tooltip-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-tooltip-animation-demo": {
      name: "animated-tooltip-animation-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-tooltip"],
      files: [{
        path: "registry/default/examples/animated-tooltip-animation-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-tooltip-animation-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-tooltip-icon-demo": {
      name: "animated-tooltip-icon-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-tooltip"],
      files: [{
        path: "registry/default/examples/animated-tooltip-icon-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-tooltip-icon-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-tooltip-status-demo": {
      name: "animated-tooltip-status-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-tooltip"],
      files: [{
        path: "registry/default/examples/animated-tooltip-status-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-tooltip-status-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-tooltip-rich-demo": {
      name: "animated-tooltip-rich-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-tooltip"],
      files: [{
        path: "registry/default/examples/animated-tooltip-rich-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-tooltip-rich-demo.tsx")),
      source: "",
      chunks: []
    },
    "rainbow-button-demo": {
      name: "rainbow-button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["rainbow-button"],
      files: [{
        path: "registry/default/examples/rainbow-button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/rainbow-button-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-toast-demo": {
      name: "animated-toast-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-toast"],
      files: [{
        path: "registry/default/examples/animated-toast-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-toast-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-toast-minimal-demo": {
      name: "animated-toast-minimal-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-toast"],
      files: [{
        path: "registry/default/examples/animated-toast-minimal-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-toast-minimal-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-toast-undo-demo": {
      name: "animated-toast-undo-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-toast"],
      files: [{
        path: "registry/default/examples/animated-toast-undo-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-toast-undo-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-toast-notification-demo": {
      name: "animated-toast-notification-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-toast"],
      files: [{
        path: "registry/default/examples/animated-toast-notification-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-toast-notification-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-toast-stacked-demo": {
      name: "animated-toast-stacked-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-toast"],
      files: [{
        path: "registry/default/examples/animated-toast-stacked-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-toast-stacked-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-toast-promise-demo": {
      name: "animated-toast-promise-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-toast"],
      files: [{
        path: "registry/default/examples/animated-toast-promise-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-toast-promise-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-basic-demo": {
      name: "animated-table-basic-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-basic-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-basic-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-sort-demo": {
      name: "animated-table-sort-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-sort-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-sort-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-search-demo": {
      name: "animated-table-search-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-search-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-search-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-select-demo": {
      name: "animated-table-select-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-select-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-select-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-expand-demo": {
      name: "animated-table-expand-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-expand-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-expand-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-column-demo": {
      name: "animated-table-column-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-column-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-column-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-pagination-demo": {
      name: "animated-table-pagination-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-pagination-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-pagination-demo.tsx")),
      source: "",
      chunks: []
    },
    "animated-table-full-demo": {
      name: "animated-table-full-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["animated-table"],
      files: [{
        path: "registry/default/examples/animated-table-full-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/animated-table-full-demo.tsx")),
      source: "",
      chunks: []
    },
    "bento-grid-custom-demo": {
      name: "bento-grid-custom-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["bento-grid"],
      files: [{
        path: "registry/default/examples/bento-grid-custom-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/bento-grid-custom-demo.tsx")),
      source: "",
      chunks: []
    },
    "bento-grid-portfolio-demo": {
      name: "bento-grid-portfolio-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["bento-grid"],
      files: [{
        path: "registry/default/examples/bento-grid-portfolio-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/bento-grid-portfolio-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-variants-demo": {
      name: "button-variants-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-variants-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-variants-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-sizes-demo": {
      name: "button-sizes-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-sizes-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-sizes-demo.tsx")),
      source: "",
      chunks: []
    },
    "button-icon-demo": {
      name: "button-icon-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-icon-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-icon-demo.tsx")),
      source: "",
      chunks: []
    },
    "file-tree-basic-demo": {
      name: "file-tree-basic-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["file-tree"],
      files: [{
        path: "registry/default/examples/file-tree-basic-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/file-tree-basic-demo.tsx")),
      source: "",
      chunks: []
    },
    "file-tree-expandable-demo": {
      name: "file-tree-expandable-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["file-tree"],
      files: [{
        path: "registry/default/examples/file-tree-expandable-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/file-tree-expandable-demo.tsx")),
      source: "",
      chunks: []
    },
    "file-tree-full-expanded-demo": {
      name: "file-tree-full-expanded-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["file-tree"],
      files: [{
        path: "registry/default/examples/file-tree-full-expanded-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/file-tree-full-expanded-demo.tsx")),
      source: "",
      chunks: []
    },
    "file-tree-selectable-demo": {
      name: "file-tree-selectable-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["file-tree"],
      files: [{
        path: "registry/default/examples/file-tree-selectable-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/file-tree-selectable-demo.tsx")),
      source: "",
      chunks: []
    },
    "file-tree-custom-icons-demo": {
      name: "file-tree-custom-icons-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["file-tree"],
      files: [{
        path: "registry/default/examples/file-tree-custom-icons-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/file-tree-custom-icons-demo.tsx")),
      source: "",
      chunks: []
    },
    "github-contributors-demo": {
      name: "github-contributors-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["github-contributors"],
      files: [{
        path: "registry/default/examples/github-contributors-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/github-contributors-demo.tsx")),
      source: "",
      chunks: []
    },
    "github-contributors-limit-demo": {
      name: "github-contributors-limit-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["github-contributors"],
      files: [{
        path: "registry/default/examples/github-contributors-limit-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/github-contributors-limit-demo.tsx")),
      source: "",
      chunks: []
    },
    "phone-card-demo": {
      name: "phone-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["phone-card"],
      files: [{
        path: "registry/default/examples/phone-card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/phone-card-demo.tsx")),
      source: "",
      chunks: []
    },
    "phone-card-image-demo": {
      name: "phone-card-image-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["phone-card"],
      files: [{
        path: "registry/default/examples/phone-card-image-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/phone-card-image-demo.tsx")),
      source: "",
      chunks: []
    },
    "rotate-text-demo": {
      name: "rotate-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["rotate-text"],
      files: [{
        path: "registry/default/examples/rotate-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/rotate-text-demo.tsx")),
      source: "",
      chunks: []
    },
    "rotate-text-custom-demo": {
      name: "rotate-text-custom-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["rotate-text"],
      files: [{
        path: "registry/default/examples/rotate-text-custom-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/rotate-text-custom-demo.tsx")),
      source: "",
      chunks: []
    },
    "vercel-tabs-demo": {
      name: "vercel-tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["vercel-tabs"],
      files: [{
        path: "registry/default/examples/vercel-tabs-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/vercel-tabs-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-demo": {
      name: "magnetic-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-intensity-demo": {
      name: "magnetic-intensity-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-intensity-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-intensity-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-range-demo": {
      name: "magnetic-range-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-range-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-range-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-action-area-demo": {
      name: "magnetic-action-area-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-action-area-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-action-area-demo.tsx")),
      source: "",
      chunks: []
    },
    "magnetic-cards-demo": {
      name: "magnetic-cards-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["magnetic"],
      files: [{
        path: "registry/default/examples/magnetic-cards-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/magnetic-cards-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-demo": {
      name: "video-player-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-compact-demo": {
      name: "video-player-compact-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-compact-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-compact-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-playlist-demo": {
      name: "video-player-playlist-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-playlist-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-playlist-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-callbacks-demo": {
      name: "video-player-callbacks-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-callbacks-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-callbacks-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-quality-demo": {
      name: "video-player-quality-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-quality-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-quality-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-captions-demo": {
      name: "video-player-captions-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-captions-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-captions-demo.tsx")),
      source: "",
      chunks: []
    },
    "video-player-timestamp-demo": {
      name: "video-player-timestamp-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["video-player"],
      files: [{
        path: "registry/default/examples/video-player-timestamp-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/video-player-timestamp-demo.tsx")),
      source: "",
      chunks: []
    },
    "command-palette-demo": {
      name: "command-palette-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["command-palette"],
      files: [{
        path: "registry/default/examples/command-palette-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/command-palette-demo.tsx")),
      source: "",
      chunks: []
    },
    "command-palette-custom-demo": {
      name: "command-palette-custom-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["command-palette"],
      files: [{
        path: "registry/default/examples/command-palette-custom-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/command-palette-custom-demo.tsx")),
      source: "",
      chunks: []
    },
    "github-star-demo": {
      name: "github-star-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["github-star"],
      files: [{
        path: "registry/default/examples/github-star-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/github-star-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-basic-demo": {
      name: "calendar-basic-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-basic-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-basic-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-range-demo": {
      name: "calendar-range-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-range-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-range-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-multiple-demo": {
      name: "calendar-multiple-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-multiple-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-multiple-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-time-demo": {
      name: "calendar-time-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-time-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-time-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-presets-demo": {
      name: "calendar-presets-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-presets-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-presets-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-constraints-demo": {
      name: "calendar-constraints-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-constraints-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-constraints-demo.tsx")),
      source: "",
      chunks: []
    },
    "calendar-full-demo": {
      name: "calendar-full-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["calender"],
      files: [{
        path: "registry/default/examples/calendar-full-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/calendar-full-demo.tsx")),
      source: "",
      chunks: []
    },
    "character-morph-demo": {
      name: "character-morph-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["character-morph"],
      files: [{
        path: "registry/default/examples/character-morph-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/character-morph-demo.tsx")),
      source: "",
      chunks: []
    },
    "character-morph-custom-demo": {
      name: "character-morph-custom-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["character-morph"],
      files: [{
        path: "registry/default/examples/character-morph-custom-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/character-morph-custom-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-demo": {
      name: "code-block-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-variants-demo": {
      name: "code-block-variants-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-variants-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-variants-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-animations-demo": {
      name: "code-block-animations-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-animations-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-animations-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-compare-demo": {
      name: "code-block-compare-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-compare-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-compare-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-tabs-demo": {
      name: "code-block-tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-tabs-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-tabs-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-terminal-demo": {
      name: "code-block-terminal-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-terminal-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-terminal-demo.tsx")),
      source: "",
      chunks: []
    },
    "code-block-glass-demo": {
      name: "code-block-glass-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: [{
        path: "registry/default/examples/code-block-glass-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/code-block-glass-demo.tsx")),
      source: "",
      chunks: []
    },
    "text-morphing-demo": {
      name: "text-morphing-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["text-morphing"],
      files: [{
        path: "registry/default/examples/text-morphing-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/text-morphing-demo.tsx")),
      source: "",
      chunks: []
    },
    "text-morphing-variants-demo": {
      name: "text-morphing-variants-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["text-morphing"],
      files: [{
        path: "registry/default/examples/text-morphing-variants-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/text-morphing-variants-demo.tsx")),
      source: "",
      chunks: []
    },
    "glitch-text-demo": {
      name: "glitch-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["glitch-text"],
      files: [{
        path: "registry/default/examples/glitch-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/glitch-text-demo.tsx")),
      source: "",
      chunks: []
    },
    "glitch-text-custom-demo": {
      name: "glitch-text-custom-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["glitch-text"],
      files: [{
        path: "registry/default/examples/glitch-text-custom-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/glitch-text-custom-demo.tsx")),
      source: "",
      chunks: []
    },
    "scroll-text-demo": {
      name: "scroll-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-text"],
      files: [{
        path: "registry/default/examples/scroll-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroll-text-demo.tsx")),
      source: "",
      chunks: []
    },
    "scroll-reveal-demo": {
      name: "scroll-reveal-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-text"],
      files: [{
        path: "registry/default/examples/scroll-reveal-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroll-reveal-demo.tsx")),
      source: "",
      chunks: []
    },
    "horizontal-scroll-text-demo": {
      name: "horizontal-scroll-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-text"],
      files: [{
        path: "registry/default/examples/horizontal-scroll-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/horizontal-scroll-text-demo.tsx")),
      source: "",
      chunks: []
    },
    "scroll-progress-text-demo": {
      name: "scroll-progress-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-text"],
      files: [{
        path: "registry/default/examples/scroll-progress-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroll-progress-text-demo.tsx")),
      source: "",
      chunks: []
    },
    "sticky-scroll-text-demo": {
      name: "sticky-scroll-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-text"],
      files: [{
        path: "registry/default/examples/sticky-scroll-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/sticky-scroll-text-demo.tsx")),
      source: "",
      chunks: []
    },
    "scroll-text-fade-up-demo": {
      name: "scroll-text-fade-up-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-text"],
      files: [{
        path: "registry/default/examples/scroll-text-fade-up-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroll-text-fade-up-demo.tsx")),
      source: "",
      chunks: []
    },
    "scroll-text-blur-demo": {
      name: "scroll-text-blur-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-text"],
      files: [{
        path: "registry/default/examples/scroll-text-blur-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroll-text-blur-demo.tsx")),
      source: "",
      chunks: []
    },
    "scroll-text-scale-demo": {
      name: "scroll-text-scale-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-text"],
      files: [{
        path: "registry/default/examples/scroll-text-scale-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroll-text-scale-demo.tsx")),
      source: "",
      chunks: []
    },
    "scroll-text-rotate-demo": {
      name: "scroll-text-rotate-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-text"],
      files: [{
        path: "registry/default/examples/scroll-text-rotate-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroll-text-rotate-demo.tsx")),
      source: "",
      chunks: []
    },
    "scroll-text-slide-left-demo": {
      name: "scroll-text-slide-left-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-text"],
      files: [{
        path: "registry/default/examples/scroll-text-slide-left-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroll-text-slide-left-demo.tsx")),
      source: "",
      chunks: []
    },
    "segmented-button-demo": {
      name: "segmented-button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["segmented-button"],
      files: [{
        path: "registry/default/examples/segmented-button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/segmented-button-demo.tsx")),
      source: "",
      chunks: []
    },
    "segmented-button-theme-demo": {
      name: "segmented-button-theme-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["segmented-button"],
      files: [{
        path: "registry/default/examples/segmented-button-theme-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/segmented-button-theme-demo.tsx")),
      source: "",
      chunks: []
    },
    "segmented-button-logo-demo": {
      name: "segmented-button-logo-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["segmented-button"],
      files: [{
        path: "registry/default/examples/segmented-button-logo-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/segmented-button-logo-demo.tsx")),
      source: "",
      chunks: []
    },
    "segmented-button-controlled-demo": {
      name: "segmented-button-controlled-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["segmented-button"],
      files: [{
        path: "registry/default/examples/segmented-button-controlled-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/segmented-button-controlled-demo.tsx")),
      source: "",
      chunks: []
    },
    "segmented-button-custom-demo": {
      name: "segmented-button-custom-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["segmented-button"],
      files: [{
        path: "registry/default/examples/segmented-button-custom-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/segmented-button-custom-demo.tsx")),
      source: "",
      chunks: []
    },
    "typewritter-text-demo": {
      name: "typewritter-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["typewritter-text"],
      files: [{
        path: "registry/default/examples/typewritter-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/typewritter-text-demo.tsx")),
      source: "",
      chunks: []
    },
    "typewritter-text-custom-demo": {
      name: "typewritter-text-custom-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["typewritter-text"],
      files: [{
        path: "registry/default/examples/typewritter-text-custom-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/typewritter-text-custom-demo.tsx")),
      source: "",
      chunks: []
    },
    "velocity-morph-demo": {
      name: "velocity-morph-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["velocity-morph"],
      files: [{
        path: "registry/default/examples/velocity-morph-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/velocity-morph-demo.tsx")),
      source: "",
      chunks: []
    },
    "velocity-morph-custom-demo": {
      name: "velocity-morph-custom-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["velocity-morph"],
      files: [{
        path: "registry/default/examples/velocity-morph-custom-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/velocity-morph-custom-demo.tsx")),
      source: "",
      chunks: []
    },
    "number-counter-demo": {
      name: "number-counter-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["number-counter"],
      files: [{
        path: "registry/default/examples/number-counter-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/number-counter-demo.tsx")),
      source: "",
      chunks: []
    },
    "rolling-counter-demo": {
      name: "rolling-counter-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["number-counter"],
      files: [{
        path: "registry/default/examples/rolling-counter-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/rolling-counter-demo.tsx")),
      source: "",
      chunks: []
    },
    "circular-counter-demo": {
      name: "circular-counter-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["number-counter"],
      files: [{
        path: "registry/default/examples/circular-counter-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/circular-counter-demo.tsx")),
      source: "",
      chunks: []
    },
    "stat-counter-demo": {
      name: "stat-counter-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["number-counter"],
      files: [{
        path: "registry/default/examples/stat-counter-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/stat-counter-demo.tsx")),
      source: "",
      chunks: []
    },
    "highlight-text-demo": {
      name: "highlight-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["highlight-text"],
      files: [{
        path: "registry/default/examples/highlight-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/highlight-text-demo.tsx")),
      source: "",
      chunks: []
    },
    "highlight-text-variants-demo": {
      name: "highlight-text-variants-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["highlight-text"],
      files: [{
        path: "registry/default/examples/highlight-text-variants-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/highlight-text-variants-demo.tsx")),
      source: "",
      chunks: []
    },
    "highlight-text-colors-demo": {
      name: "highlight-text-colors-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["highlight-text"],
      files: [{
        path: "registry/default/examples/highlight-text-colors-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/highlight-text-colors-demo.tsx")),
      source: "",
      chunks: []
    },
    "gooey-text-morphing-demo": {
      name: "gooey-text-morphing-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["gooey-text-morphing"],
      files: [{
        path: "registry/default/examples/gooey-text-morphing-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/gooey-text-morphing-demo.tsx")),
      source: "",
      chunks: []
    },
    "feedback-widget-demo": {
      name: "feedback-widget-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["feedback-widget"],
      files: [{
        path: "registry/default/examples/feedback-widget-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/feedback-widget-demo.tsx")),
      source: "",
      chunks: []
    },
    "feedback-widget-custom-label-demo": {
      name: "feedback-widget-custom-label-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["feedback-widget"],
      files: [{
        path: "registry/default/examples/feedback-widget-custom-label-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/feedback-widget-custom-label-demo.tsx")),
      source: "",
      chunks: []
    },
  },
}
